module Evergreen.Migrate.V8 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V7.Types
import Evergreen.V8.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V7.Types.FrontendModel -> ModelMigration Evergreen.V8.Types.FrontendModel Evergreen.V8.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V7.Types.BackendModel -> ModelMigration Evergreen.V8.Types.BackendModel Evergreen.V8.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V7.Types.FrontendMsg -> MsgMigration Evergreen.V8.Types.FrontendMsg Evergreen.V8.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V7.Types.ToBackend -> MsgMigration Evergreen.V8.Types.ToBackend Evergreen.V8.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V7.Types.BackendMsg -> MsgMigration Evergreen.V8.Types.BackendMsg Evergreen.V8.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V7.Types.ToFrontend -> MsgMigration Evergreen.V8.Types.ToFrontend Evergreen.V8.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_Types_FrontendModel : Evergreen.V7.Types.FrontendModel -> Evergreen.V8.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , version = "-"
    , zone = old.zone
    , time = old.time
    , size = old.size
    , dateHidden = old.dateHidden
    , mouseOver = old.mouseOver
    , schedule = old.schedule
    , scheduleShown = old.scheduleShown
    , currentHourInput = old.currentHourInput
    , currentMinutesInput = old.currentMinutesInput
    , currentDescInput = old.currentDescInput
    , currentPoolname = old.currentPoolname
    , poolNameShown = False
    }


migrate_Types_FrontendMsg : Evergreen.V7.Types.FrontendMsg -> Evergreen.V8.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V7.Types.UrlClicked p0 ->
            Evergreen.V8.Types.UrlClicked p0

        Evergreen.V7.Types.UrlChanged p0 ->
            Evergreen.V8.Types.UrlChanged p0

        Evergreen.V7.Types.NoOpFrontendMsg ->
            Evergreen.V8.Types.NoOpFrontendMsg

        Evergreen.V7.Types.Tick p0 ->
            Evergreen.V8.Types.Tick p0

        Evergreen.V7.Types.AdjustTimeZone p0 ->
            Evergreen.V8.Types.AdjustTimeZone p0

        Evergreen.V7.Types.ViewportReceived p0 ->
            Evergreen.V8.Types.ViewportReceived p0

        Evergreen.V7.Types.Resized p0 p1 ->
            Evergreen.V8.Types.Resized p0 p1

        Evergreen.V7.Types.DateToggled ->
            Evergreen.V8.Types.DateToggled

        Evergreen.V7.Types.MouseOver p0 ->
            Evergreen.V8.Types.MouseOver p0

        Evergreen.V7.Types.ScheduleToggled ->
            Evergreen.V8.Types.ScheduleToggled

        Evergreen.V7.Types.HourInputChanged p0 ->
            Evergreen.V8.Types.HourInputChanged p0

        Evergreen.V7.Types.MinutesInputChanged p0 ->
            Evergreen.V8.Types.MinutesInputChanged p0

        Evergreen.V7.Types.DescInputChanged p0 ->
            Evergreen.V8.Types.DescInputChanged p0

        Evergreen.V7.Types.AddEventPressed ->
            Evergreen.V8.Types.AddEventPressed

        Evergreen.V7.Types.DeleteEventPressed p0 ->
            Evergreen.V8.Types.DeleteEventPressed p0

        Evergreen.V7.Types.PoolnameInputChanged p0 ->
            Evergreen.V8.Types.PoolnameInputChanged p0

        Evergreen.V7.Types.AddToPoolRequested ->
            Evergreen.V8.Types.AddToPoolRequested
